{% set name = "boto3" %}
{% set version = "1.43.24" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/boto/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 03a702a7606ae89676570c504410deef2b9cefe6d31cf1b051f7de2adb789c68

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - botocore >=1.43.24,<1.44.0
    - jmespath >=0.7.1,<2.0.0
    - s3transfer >=0.18.0,<0.19.0
  run_constrained:
    # botocore[crt]>=1.21.0,<2.0a0: from botocore 1.43.24 - awscrt 0.32.2
    - awscrt 0.32.2

test:
  source_files:
    - tests
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3
  commands:
    - pip check
    # Integration tests are required to validate real AWS services like S3 and SQS, which are not available in our environment.
    # Error example:
    #   - botocore.exceptions.NoCredentialsError: Unable to locate credentials
    #   - botocore.exceptions.ClientError: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
    # Skipping integration tests:
    - pytest -v tests --ignore=tests/integration/
  requires:
    - pip
    - pytest

about:
  home: https://aws.amazon.com/sdk-for-python
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.amazonaws.com/v1/documentation/api/latest/index.html
  dev_url: https://github.com/boto/boto3

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
    - ocefpaf