{% set name = "boto3" %}
{% set version = "1.34.82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcdb84936b04d5f78c8c8667b65bf5b9803cf39fd25bb7fe57ba237074e36171

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - botocore >=1.34.82,<1.35.0
    - jmespath >=0.7.1,<2.0.0
    - s3transfer >=0.10.0,<0.11.0

test:
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://aws.amazon.com/sdk-for-python/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.amazonaws.com/v1/documentation/api/latest/index.html
  dev_url: https://github.com/boto/boto3

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
    - ocefpaf
