{% set name = "boto3" %}
{% set version = "1.40.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boto/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e7de36378e605d9798297456e7dc452896e3001e72395396ad9e16890adb85e2

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - botocore >=1.40.54,<1.41.0
    - jmespath >=0.7.1,<2.0.0
    - s3transfer >=0.14.0,<0.15.0
  run_constrained:
    # https://github.com/boto/boto3/blob/1.37.10/setup.cfg#L11C1-L11C35
    # pip install --dry-run "botocore[crt]>=1.21.0,<2.0a0"
    # pip output is:
    # Collecting awscrt==0.23.8 (from botocore[crt]<2.0a0,>=1.21.0)
    - awscrt 0.23.8
    - botocore >=1.21.0,<2.0a0

# Integration tests are required to validate real AWS services like S3 and SQS, which are not available in our environment.
# Error example:
#   - botocore.exceptions.NoCredentialsError: Unable to locate credentials
#   - botocore.exceptions.ClientError: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
# Skipping integration tests:
test:
  source_files:
    - tests
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3
  commands:
    - pip check
    - pytest -v tests --ignore=tests/integration/
  requires:
    - pip
    - pytest

about:
  home: https://aws.amazon.com/sdk-for-python
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.amazonaws.com/v1/documentation/api/latest/index.html
  dev_url: https://github.com/boto/boto3

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
    - ocefpaf
