travis:
  secure:
    BINSTAR_TOKEN: BdDDAiaurrwXD2L3xVnZ/rKBbhrQtXnuzkumyDsweNwvD4ZHQ1kZsfzW1ym1TADMvyVtkbzvFOvhjzcqQ4rgMrHHohCGYtlaiEC97xNcJUOdCkMN8TE8XtBrrY+pExVpL7r5p6jEd9xloeTu4N2wCR7zhXIQtewqvaPG6GtwE8mgSwnoJcq4m99vsesA6F7DBGFO1/fH9vKu198hVcQFWQDV3PylozDWcN0NW6ik+ZTBIk6m0vq3lH/ang1LoRtm52mlaIGqECfKCtk+np4amhEcYhCfJzENCcRKaRalvGq/sSMkV8bFFRYbgOCCZu//kTxxt38TrIIc4IayZwVf82mTb4IQXx43vd/cULJjxvFPu1UkKbRmTxSdVsTxCTykPpcgMK2JThv1QRBOXdGDtrPmTAn8aI1TunQnE/JhFwUGXOY8qcMc1Wxwv5gI5GOGi3/9HusGgw30DpmIPVhX9WUyGxfMYKIXr4+551MPqnFTBAm4fsO5HEI/MgsyzIYK8eMI53gZ2PwxPjVQowOmHCVOrmfM0L0ww4maa1Wei6GXNMm8+wnIBqNH77IBn1lHcTq2bItLTLmRF7qrylpMfzNRuL6fq/2mBMJwSXlhh6vP1ddMqYMj6Qy/1WIx1IzsgVhOoDa9uoYl1luz8BCWw1qlUEkJImr2qQpf+NTkyGw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
